# Generated by Django 5.1 on 2024-08-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='user',
            new_name='renter',
        ),
    ]
